#!/usr/local/bin/bash

# set the path for our tests
PATH=$PATH:/usr/local/bin:/usr/local/sbin:.

REPOS="$1"  # /svn/nsd or /svn/libdns
REV="$2"

# please edit these to suit your needs
TPKG=/home/miekg/svn/tpkg/trunk/tpkg
MAILTO="ldns-team@nlnetlabs.nl"
MAILSUB="[svn: ldns] $REV status"
REPOPATH="trunk"
TESTDIR="test"
BUILD_DIR=`mktemp -d /tmp/XXXXXX`
if [ ! -d $BUILD_DIR ]; then
        exit 0
fi
MAIL_FILE=`mktemp /tmp/XXXXXXX`

# checkout to $BUILD_DIR, assume local checkout
/usr/local/bin/svn co -r$REV file://$REPOS/$REPOPATH $BUILD_DIR
( cd $BUILD_DIR ; svn log -r$REV > $MAIL_FILE )

# set the path for our sibling test scripts
echo "PATH=$PATH" > $BUILD_DIR/$TESTDIR/.tpkg.var

# RUN THE TESTS
for tests in $BUILD_DIR/$TESTDIR/*.tpkg ; do
        /usr/bin/nice /usr/local/bin/bash \
        $TPKG -b $BUILD_DIR/$TESTDIR -a $BUILD_DIR exe `basename $tests`
done

/usr/local/bin/bash $TPKG -b $BUILD_DIR/$TESTDIR report 2>&1 >> $MAIL_FILE
/usr/local/bin/bash $TPKG -b $BUILD_DIR/$TESTDIR clean >> $MAIL_FILE
# END

# SVN STUFF
( cd $BUILD_DIR ; svn diff -rPREV:$REV >> $MAIL_FILE )

rm -rf $BUILD_DIR

cat $MAIL_FILE | mail -s "${MAILSUB}" $MAILTO
rm -f $MAIL_FILE
